const lorems = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Etiam erat velit scelerisque in dictum. Facilisi etiam dignissim diam quis enim. Id eu nisl nunc mi. Mattis enim ut tellus elementum sagittis. Augue neque gravida in fermentum et sollicitudin ac. Feugiat vivamus at augue eget arcu dictum. Nec ullamcorper sit amet risus nullam eget. Aliquet lectus proin nibh nisl condimentum id venenatis a. In nulla posuere sollicitudin aliquam ultrices sagittis orci.",
    "Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam quis. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Mi bibendum neque egestas congue quisque egestas diam in arcu. Phasellus vestibulum lorem sed risus. Nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum. Blandit aliquam etiam erat velit scelerisque in dictum non. Volutpat consequat mauris nunc congue nisi vitae suscipit. Semper viverra nam libero justo laoreet sit amet cursus sit. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae proin. Feugiat nibh sed pulvinar proin gravida. Id diam vel quam elementum pulvinar etiam non. Quisque egestas diam in arcu cursus euismod quis viverra nibh. Mattis enim ut tellus elementum. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Nunc mattis enim ut tellus elementum sagittis vitae.",
    "Aliquet nibh praesent tristique magna sit amet purus gravida. Amet purus gravida quis blandit turpis cursus in. Suspendisse in est ante in nibh mauris cursus mattis molestie. Tincidunt arcu non sodales neque sodales ut etiam sit. Urna porttitor rhoncus dolor purus non enim praesent elementum facilisis. Laoreet non curabitur gravida arcu ac. Magnis dis parturient montes nascetur ridiculus mus mauris. Ac placerat vestibulum lectus mauris. Ornare massa eget egestas purus viverra. Scelerisque felis imperdiet proin fermentum leo vel orci porta non.",
    "Tellus mauris a diam maecenas sed enim. Aliquam malesuada bibendum arcu vitae elementum curabitur. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Pellentesque habitant morbi tristique senectus et netus et malesuada. Dapibus ultrices in iaculis nunc sed. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. In egestas erat imperdiet sed euismod. Vulputate sapien nec sagittis aliquam malesuada. Suspendisse faucibus interdum posuere lorem ipsum. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Amet aliquam id diam maecenas ultricies mi eget mauris pharetra. Auctor augue mauris augue neque gravida. Sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis. Tellus at urna condimentum mattis pellentesque id. Commodo quis imperdiet massa tincidunt. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. At erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Odio aenean sed adipiscing diam donec.",
    "Morbi leo urna molestie at elementum eu. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. Tempus iaculis urna id volutpat. Pharetra diam sit amet nisl suscipit. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Tempor orci dapibus ultrices in. Pellentesque eu tincidunt tortor aliquam. Ultrices in iaculis nunc sed augue lacus viverra vitae. Cursus in hac habitasse platea dictumst quisque sagittis. Fusce id velit ut tortor. Sagittis vitae et leo duis. Morbi tincidunt augue interdum velit euismod in pellentesque.",
    "Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Rhoncus mattis rhoncus urna neque viverra. Est ante in nibh mauris cursus mattis molestie a. Est sit amet facilisis magna etiam tempor. Ac tincidunt vitae semper quis lectus. Tempus imperdiet nulla malesuada pellentesque. Placerat in egestas erat imperdiet sed euismod nisi porta. Posuere lorem ipsum dolor sit. Et pharetra pharetra massa massa ultricies. Proin sagittis nisl rhoncus mattis. A diam maecenas sed enim ut sem viverra. Ut placerat orci nulla pellentesque dignissim enim sit amet venenatis. Semper viverra nam libero justo laoreet sit. Neque volutpat ac tincidunt vitae semper quis lectus nulla at. Vulputate eu scelerisque felis imperdiet. In iaculis nunc sed augue lacus viverra vitae congue. Metus dictum at tempor commodo ullamcorper a lacus. In ante metus dictum at tempor commodo.",
    "Pretium aenean pharetra magna ac placerat vestibulum. Ac ut consequat semper viverra nam. Neque aliquam vestibulum morbi blandit. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Et netus et malesuada fames ac turpis egestas. Blandit aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus. Aliquet porttitor lacus luctus accumsan. Gravida quis blandit turpis cursus in hac habitasse platea. Interdum velit laoreet id donec ultrices tincidunt. Id ornare arcu odio ut sem nulla pharetra diam sit. Proin fermentum leo vel orci porta non pulvinar neque. Sit amet massa vitae tortor condimentum lacinia quis. Senectus et netus et malesuada fames. Lobortis mattis aliquam faucibus purus in massa. Amet mattis vulputate enim nulla.",
    "Et ultrices neque ornare aenean. Tortor at risus viverra adipiscing at in. Eu scelerisque felis imperdiet proin fermentum. Eu volutpat odio facilisis mauris sit. Nibh venenatis cras sed felis eget velit aliquet. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Et sollicitudin ac orci phasellus egestas tellus rutrum. Nunc lobortis mattis aliquam faucibus purus in massa. Lectus quam id leo in vitae.",
    "Suspendisse sed nisi lacus sed viverra tellus in. Mi eget mauris pharetra et ultrices neque ornare aenean. Scelerisque in dictum non consectetur. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. Leo integer malesuada nunc vel risus commodo. Sed nisi lacus sed viverra. Egestas maecenas pharetra convallis posuere morbi leo urna. Neque egestas congue quisque egestas diam in arcu cursus euismod. Eu facilisis sed odio morbi quis. Amet consectetur adipiscing elit ut aliquam purus. Quam pellentesque nec nam aliquam. Fermentum leo vel orci porta non pulvinar neque. Purus semper eget duis at tellus at."
]

const generateButton = document.querySelector(".generateButton");
const howMany = document.getElementById("howMany");
const placeForParagraphs = document.querySelector(".generatedParagraphs");

generateButton.addEventListener("click", function(){
    
    let randomNumber = Math.floor(Math.random()*lorems.length);
    console.log(typeof howMany);
    if(howMany.value <= 0 || howMany.value > 9){
        
        placeForParagraphs.innerHTML = `<p class="generatingText">${lorems[randomNumber]}</p>`;
    }
    else{
        let someText = lorems.slice(0,howMany.value);
        someText = someText.map(function(lorem){
            return `<p class="generatingText">${lorem}</p>`;
        }).join('')
       
        placeForParagraphs.innerHTML = someText;
    }
});